// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI (migrations, introspection, studio) uses the DIRECT connection
    // (Supabase port 5432) to bypass the Supavisor transaction pooler.
    url: process.env["DIRECT_URL"],
  },
});
